<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Domain\Entities\Entities\ji5w4gww.t1e~" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\netauth.contract\NetAuth.Contract.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="DapperExtensions" Version="1.7.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.0.1" />
	<PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.19.180" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Domain\Entities\CoreVM\" />
  </ItemGroup>
</Project>
