//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Should not exceed 150 characters..
        /// </summary>
        public static string AcmeCreateRequestValidator_FirstName_Length {
            get {
                return ResourceManager.GetString("AcmeCreateRequestValidator_FirstName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string AcmeCreateRequestValidator_FirstName_NotEmpty {
            get {
                return ResourceManager.GetString("AcmeCreateRequestValidator_FirstName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial Number is requried..
        /// </summary>
        public static string CallRingOutRequestValidator_DialNumber_Empty {
            get {
                return ResourceManager.GetString("CallRingOutRequestValidator_DialNumber_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial Number should not exceed more than 15 characters..
        /// </summary>
        public static string CallRingOutRequestValidator_DialNumber_Length {
            get {
                return ResourceManager.GetString("CallRingOutRequestValidator_DialNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarrierId is Required.
        /// </summary>
        public static string ContactCreateRequestValidator_CarrierId_NotEmpty {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_CarrierId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name should not exceed 30 characters..
        /// </summary>
        public static string ContactCreateRequestValidator_FirstName_Length {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_FirstName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required..
        /// </summary>
        public static string ContactCreateRequestValidator_FirstName_NotEmpty {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_FirstName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title should not exceed more than 60 characters..
        /// </summary>
        public static string ContactCreateRequestValidator_JobTitle_Length {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_JobTitle_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name should not exceed more than 30 characters..
        /// </summary>
        public static string ContactCreateRequestValidator_LastName_Length {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_LastName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required..
        /// </summary>
        public static string ContactCreateRequestValidator_LastName_NotEmpty {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_LastName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1 should not exceed more than 60 characters..
        /// </summary>
        public static string ContactCreateRequestValidator_Office1AddressLine1_Length {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_Office1AddressLine1_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2 should not exceed more than 60 characters..
        /// </summary>
        public static string ContactCreateRequestValidator_Office1AddressLine2_Length {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_Office1AddressLine2_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City should not exceed more than 60 characters..
        /// </summary>
        public static string ContactCreateRequestValidator_Office1City_Length {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_Office1City_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name is required..
        /// </summary>
        public static string ContactCreateRequestValidator_Office1City_NotEmpty {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_Office1City_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address..
        /// </summary>
        public static string ContactCreateRequestValidator_Office1Email_NotEmpty {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_Office1Email_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension should not exceed more than 5 characters..
        /// </summary>
        public static string ContactCreateRequestValidator_Office1Extension_Length {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_Office1Extension_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select State..
        /// </summary>
        public static string ContactCreateRequestValidator_Office1State_NotEmpty {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_Office1State_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect Id is required..
        /// </summary>
        public static string ContactCreateRequestValidator_ProspectId_NotEmpty {
            get {
                return ResourceManager.GetString("ContactCreateRequestValidator_ProspectId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcmeProductId is Required.
        /// </summary>
        public static string CreateAcmeProductDetailValidator_AcmeProductId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAcmeProductDetailValidator_AcmeProductId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WbaId is required..
        /// </summary>
        public static string CreateAdditionalInformationRequest_WbaId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAdditionalInformationRequest_WbaId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date is required.
        /// </summary>
        public static string CreateAppointmentsValidator_DateofAppointment_Format {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_DateofAppointment_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date Should not be empty .
        /// </summary>
        public static string CreateAppointmentsValidator_DateofAppointment_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_DateofAppointment_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Appointment End date .
        /// </summary>
        public static string CreateAppointmentsValidator_EndTime_Format {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_EndTime_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment End Date is required .
        /// </summary>
        public static string CreateAppointmentsValidator_EndTime_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_EndTime_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Note is required.
        /// </summary>
        public static string CreateAppointmentsValidator_Notes_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_Notes_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Appointment Start date.
        /// </summary>
        public static string CreateAppointmentsValidator_StartTime_Format {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_StartTime_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Start Date is required.
        /// </summary>
        public static string CreateAppointmentsValidator_StartTime_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_StartTime_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Subject is required.
        /// </summary>
        public static string CreateAppointmentsValidator_Subject_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_Subject_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment TypeofVisit is required .
        /// </summary>
        public static string CreateAppointmentsValidator_TypeofVisit_NotEmpty {
            get {
                return ResourceManager.GetString("CreateAppointmentsValidator_TypeofVisit_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Carrier already exists..
        /// </summary>
        public static string CreateCarrierMaintaineneceRequestValidator_Carrier_Duplicate {
            get {
                return ResourceManager.GetString("CreateCarrierMaintaineneceRequestValidator_Carrier_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Name is required..
        /// </summary>
        public static string CreateCarrierMaintaineneceRequestValidator_CarrierId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateCarrierMaintaineneceRequestValidator_CarrierId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Carrier with the same NAIC code already exists ..
        /// </summary>
        public static string CreateCarrierMaintaineneceRequestValidator_CarrierNAIC_Duplicate {
            get {
                return ResourceManager.GetString("CreateCarrierMaintaineneceRequestValidator_CarrierNAIC_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Carrier already exists..
        /// </summary>
        public static string CreateCarrierMaintaineneceRequestValidator_CarrierName_Duplicate {
            get {
                return ResourceManager.GetString("CreateCarrierMaintaineneceRequestValidator_CarrierName_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naic Code is required..
        /// </summary>
        public static string CreateCarrierMaintaineneceRequestValidator_NAIC_NotEmpty {
            get {
                return ResourceManager.GetString("CreateCarrierMaintaineneceRequestValidator_NAIC_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is required..
        /// </summary>
        public static string CreateCarrierMaintaineneceRequestValidator_TypeId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateCarrierMaintaineneceRequestValidator_TypeId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email_to is required..
        /// </summary>
        public static string CreateClientRequestValidator_email_to_Required {
            get {
                return ResourceManager.GetString("CreateClientRequestValidator_email_to_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        public static string CreateConatctRequestValidator_CarrierEmail_Duplicate {
            get {
                return ResourceManager.GetString("CreateConatctRequestValidator_CarrierEmail_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone Number should be 10 Digit..
        /// </summary>
        public static string CreateConatctRequestValidator_PhoneNumber_Length {
            get {
                return ResourceManager.GetString("CreateConatctRequestValidator_PhoneNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to create at least one Primary Contact for this Prospect..
        /// </summary>
        public static string CreateContactRequestValidator_IsPrimaryDuplicate {
            get {
                return ResourceManager.GetString("CreateContactRequestValidator_IsPrimaryDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to create at least one Primary Contact for this Prospect..
        /// </summary>
        public static string CreateContactRequestValidator_PrimaryContact {
            get {
                return ResourceManager.GetString("CreateContactRequestValidator_PrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CallDuration..
        /// </summary>
        public static string CreateDialRequestValidator_CallDuration_Format {
            get {
                return ResourceManager.GetString("CreateDialRequestValidator_CallDuration_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition is required..
        /// </summary>
        public static string CreateDialsRequestValidator_DispositionId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateDialsRequestValidator_DispositionId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition Id must be greater than 0..
        /// </summary>
        public static string CreateDialsRequestValidator_DispositionId_NotZero {
            get {
                return ResourceManager.GetString("CreateDialsRequestValidator_DispositionId_NotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name should&apos;nt be empty..
        /// </summary>
        public static string CreateDialsRequestValidator_FirstName_NotEmpty {
            get {
                return ResourceManager.GetString("CreateDialsRequestValidator_FirstName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name should&apos;nt be empty..
        /// </summary>
        public static string CreateDialsRequestValidator_LastName_NotEmpty {
            get {
                return ResourceManager.GetString("CreateDialsRequestValidator_LastName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile should&apos;nt be empty..
        /// </summary>
        public static string CreateDialsRequestValidator_Mobile_NotEmpty {
            get {
                return ResourceManager.GetString("CreateDialsRequestValidator_Mobile_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a disposition value..
        /// </summary>
        public static string CreateDispositionRequestValidator_DispositionId_required {
            get {
                return ResourceManager.GetString("CreateDispositionRequestValidator_DispositionId_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WbaId does not exist..
        /// </summary>
        public static string CreateEpicRequestValidator_WbaId_Valid {
            get {
                return ResourceManager.GetString("CreateEpicRequestValidator_WbaId_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists..
        /// </summary>
        public static string CreateIndustryTypeCodeValidatorRequest_ClassCode_Duplicate {
            get {
                return ResourceManager.GetString("CreateIndustryTypeCodeValidatorRequest_ClassCode_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProspectId does not exists. .
        /// </summary>
        public static string CreateIndustryTypeCodeValidatorRequest_ProspectId_Valid {
            get {
                return ResourceManager.GetString("CreateIndustryTypeCodeValidatorRequest_ProspectId_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list name that you have entered matches another list that you have access to. Please enter another name for this list, lists cannot be overwritten..
        /// </summary>
        public static string CreateListRequestValidator_ListName_Exists {
            get {
                return ResourceManager.GetString("CreateListRequestValidator_ListName_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name should not exceed more than 100 characters..
        /// </summary>
        public static string CreateListRequestValidator_ListName_Length {
            get {
                return ResourceManager.GetString("CreateListRequestValidator_ListName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name is Required..
        /// </summary>
        public static string CreateListRequestValidator_ListName_NotEmpty {
            get {
                return ResourceManager.GetString("CreateListRequestValidator_ListName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary filter Not blank..
        /// </summary>
        public static string CreateListRequestValidator_Primary_NotNull {
            get {
                return ResourceManager.GetString("CreateListRequestValidator_Primary_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Type is required..
        /// </summary>
        public static string CreateListRequestValidator_SaveAsType_NotEmpty {
            get {
                return ResourceManager.GetString("CreateListRequestValidator_SaveAsType_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of List is Requird..
        /// </summary>
        public static string CreateListRequestValidator_TypeOfList_NotEmpty {
            get {
                return ResourceManager.GetString("CreateListRequestValidator_TypeOfList_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string CreateNotesRequestValidator_Description_Format {
            get {
                return ResourceManager.GetString("CreateNotesRequestValidator_Description_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select disposition value..
        /// </summary>
        public static string CreateNotesRequestValidator_DispositionId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateNotesRequestValidator_DispositionId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid record date..
        /// </summary>
        public static string CreateNotesRequestValidator_RecordDate_Format {
            get {
                return ResourceManager.GetString("CreateNotesRequestValidator_RecordDate_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active can not be null.
        /// </summary>
        public static string CreateProspectInactiveValidator_IsActve_NotNull {
            get {
                return ResourceManager.GetString("CreateProspectInactiveValidator_IsActve_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name should not exceed more than 60 characters..
        /// </summary>
        public static string CreateProspectRequestValidator_City_Length {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_City_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name is required..
        /// </summary>
        public static string CreateProspectRequestValidator_City_NotEmpty {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_City_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Phone Number or Email Address is required..
        /// </summary>
        public static string CreateProspectRequestValidator_Email_Or_PhoneNumber {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_Email_Or_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address..
        /// </summary>
        public static string CreateProspectRequestValidator_EmailAddress_Format {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_EmailAddress_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is required..
        /// </summary>
        public static string CreateProspectRequestValidator_EmailAddress_NotEmpty {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_EmailAddress_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number should not exceed 10 digits..
        /// </summary>
        public static string CreateProspectRequestValidator_PhoneNumber_Length {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_PhoneNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is required..
        /// </summary>
        public static string CreateProspectRequestValidator_PhoneNumber_NotEmpty {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_PhoneNumber_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name should not exceed more than 200 characters..
        /// </summary>
        public static string CreateProspectRequestValidator_ProspectName_Length {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_ProspectName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required..
        /// </summary>
        public static string CreateProspectRequestValidator_ProspectName_NotEmpty {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_ProspectName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select State..
        /// </summary>
        public static string CreateProspectRequestValidator_State_NotEmpty {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_State_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Zip Code..
        /// </summary>
        public static string CreateProspectRequestValidator_Zipcode_Format {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_Zipcode_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code is required..
        /// </summary>
        public static string CreateProspectRequestValidator_Zipcode_NotEmpty {
            get {
                return ResourceManager.GetString("CreateProspectRequestValidator_Zipcode_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name should not exceed more than 60 characters..
        /// </summary>
        public static string CreateQuoteRequestValidator_ContactName_Length {
            get {
                return ResourceManager.GetString("CreateQuoteRequestValidator_ContactName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name is required..
        /// </summary>
        public static string CreateQuoteRequestValidator_ContactName_NotEmpty {
            get {
                return ResourceManager.GetString("CreateQuoteRequestValidator_ContactName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority is Required..
        /// </summary>
        public static string CreateRecallRequestValidator_PriorityId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateRecallRequestValidator_PriorityId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Date is Required...
        /// </summary>
        public static string CreateRecallRequestValidator_RecallDate_NotEmpty {
            get {
                return ResourceManager.GetString("CreateRecallRequestValidator_RecallDate_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Recall Time..
        /// </summary>
        public static string CreateRecallRequestValidator_RecallTime_Format {
            get {
                return ResourceManager.GetString("CreateRecallRequestValidator_RecallTime_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Time is Required..
        /// </summary>
        public static string CreateRecallRequestValidator_RecallTime_NotEmpty {
            get {
                return ResourceManager.GetString("CreateRecallRequestValidator_RecallTime_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity is required..
        /// </summary>
        public static string CreateTagRequestValidator_Entity_Required {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_Entity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Tag is required..
        /// </summary>
        public static string CreateTagRequestValidator_ParentTag_Required {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_ParentTag_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect Id is required..
        /// </summary>
        public static string CreateTagRequestValidator_ProspectId_required {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_ProspectId_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name should not exceed more than 100 characters..
        /// </summary>
        public static string CreateTagRequestValidator_TagDescription_Length {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_TagDescription_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name is required ..
        /// </summary>
        public static string CreateTagRequestValidator_TagDescription_NotEmpty {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_TagDescription_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tag already exists with the same Entity..
        /// </summary>
        public static string CreateTagRequestValidator_TagDuplicate {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_TagDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Names are required..
        /// </summary>
        public static string CreateTagRequestValidator_TagName_Required {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_TagName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags cannot be null al least one tags must be there.
        /// </summary>
        public static string CreateTagRequestValidator_Tags_required {
            get {
                return ResourceManager.GetString("CreateTagRequestValidator_Tags_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified title already exists..
        /// </summary>
        public static string CreateTodoListCommandValidator_Title_Exists {
            get {
                return ResourceManager.GetString("CreateTodoListCommandValidator_Title_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must not exceed 200 characters..
        /// </summary>
        public static string CreateTodoListCommandValidator_Title_Length {
            get {
                return ResourceManager.GetString("CreateTodoListCommandValidator_Title_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string CreateTodoListCommandValidator_Title_Required {
            get {
                return ResourceManager.GetString("CreateTodoListCommandValidator_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name should&apos;nt be empty..
        /// </summary>
        public static string CreateUserRequestValidator_display_name_NotEmpty {
            get {
                return ResourceManager.GetString("CreateUserRequestValidator_display_name_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email should not be empty..
        /// </summary>
        public static string CreateUserRequestValidator_Email_NotEmpty {
            get {
                return ResourceManager.GetString("CreateUserRequestValidator_Email_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId should&apos;nt be empty..
        /// </summary>
        public static string CreateUserRequestValidator_Id_NotEmpty {
            get {
                return ResourceManager.GetString("CreateUserRequestValidator_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oid should&apos;nt be empty..
        /// </summary>
        public static string CreateUserRequestValidator_oid_NotEmpty {
            get {
                return ResourceManager.GetString("CreateUserRequestValidator_oid_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage Id is required. .
        /// </summary>
        public static string CreateWbaGLCoverageRatingValidatorRequest_CoverageId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWbaGLCoverageRatingValidatorRequest_CoverageId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line is required..
        /// </summary>
        public static string CreateWBARequestValidator_BusinessLineId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_BusinessLineId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Status is required..
        /// </summary>
        public static string CreateWBARequestValidator_BusinessStatusId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_BusinessStatusId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact id is required..
        /// </summary>
        public static string CreateWBARequestValidator_ContactId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_ContactId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Effective Date..
        /// </summary>
        public static string CreateWBARequestValidator_EffectiveDate {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Employee Identification Number..
        /// </summary>
        public static string CreateWBARequestValidator_EIN_NotMatchWithDB {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_EIN_NotMatchWithDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid company name..
        /// </summary>
        public static string CreateWBARequestValidator_ProspectName_NotExist {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_ProspectName_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Premium should not exceed more than 60 digits..
        /// </summary>
        public static string CreateWBARequestValidator_TargetPremium_Length {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_TargetPremium_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Premium is required..
        /// </summary>
        public static string CreateWBARequestValidator_TargetPremium_Required {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_TargetPremium_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing user is required..
        /// </summary>
        public static string CreateWBARequestValidator_UserId_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWBARequestValidator_UserId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class code is required..
        /// </summary>
        public static string CreateWbaWorkerCompensationRatingValidatorRequest_ClassCode_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWbaWorkerCompensationRatingValidatorRequest_ClassCode_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class code not blank..
        /// </summary>
        public static string CreateWbaWorkerCompensationRatingValidatorRequest_ClassCoden_NotNull {
            get {
                return ResourceManager.GetString("CreateWbaWorkerCompensationRatingValidatorRequest_ClassCoden_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required..
        /// </summary>
        public static string CreateWbaWorkerCompensationRatingValidatorRequest_Location_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWbaWorkerCompensationRatingValidatorRequest_Location_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not blank..
        /// </summary>
        public static string CreateWbaWorkerCompensationRatingValidatorRequest_Location_NotNull {
            get {
                return ResourceManager.GetString("CreateWbaWorkerCompensationRatingValidatorRequest_Location_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountManager ID is required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_AccountManagerId_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_AccountManagerId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Carrier ID should be required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_ExpireingCarrierId_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_ExpireingCarrierId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Premium should be not empty.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_ExpiringPremium_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_ExpiringPremium_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Premium should be required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_ExpiringPremium_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_ExpiringPremium_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Revenue should be not required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_ExpiringRevenue_NotEmpty {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_ExpiringRevenue_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Revenue should be required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_ExpiringRevenue_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_ExpiringRevenue_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadGenerate ID should be required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_LeadGenerateId_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_LeadGenerateId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID should be required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_OwnerId_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_OwnerId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Description should be required..
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_PolicyDescription_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_PolicyDescription_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress ID is required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_ProgressId_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_ProgressId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result ID is required.
        /// </summary>
        public static string CreateWhiteBoardActivityRequestValidator_ResultId_Required {
            get {
                return ResourceManager.GetString("CreateWhiteBoardActivityRequestValidator_ResultId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating a primary contact requires assigning any of the other contacts as primary contact.
        /// </summary>
        public static string DeleteContactRequestValidator_PrimaryContact {
            get {
                return ResourceManager.GetString("DeleteContactRequestValidator_PrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to delete this note..
        /// </summary>
        public static string DeleteNotesRequestValidator_NotesAuth {
            get {
                return ResourceManager.GetString("DeleteNotesRequestValidator_NotesAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate prospect/invalid data in this file..
        /// </summary>
        public static string ImportProspectFileInDatabaseRequestValidator_DuplicateProspectFromCsv {
            get {
                return ResourceManager.GetString("ImportProspectFileInDatabaseRequestValidator_DuplicateProspectFromCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required  fields not matched with file column..
        /// </summary>
        public static string ImportProspectFileInDatabaseRequestValidator_RequiredProspectFieldsShouldBeMatch {
            get {
                return ResourceManager.GetString("ImportProspectFileInDatabaseRequestValidator_RequiredProspectFieldsShouldBeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File should be .csv extension only.
        /// </summary>
        public static string ImportProspectRequestValidator_FileShouldBeCsv {
            get {
                return ResourceManager.GetString("ImportProspectRequestValidator_FileShouldBeCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File should have records.
        /// </summary>
        public static string ImportProspectRequestValidator_FileShouldHaveRecord {
            get {
                return ResourceManager.GetString("ImportProspectRequestValidator_FileShouldHaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records imported successfully.
        /// </summary>
        public static string ProspectImportFromCsvFileInDatabaseRequest_prospectimported {
            get {
                return ResourceManager.GetString("ProspectImportFromCsvFileInDatabaseRequest_prospectimported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessfully imported.
        /// </summary>
        public static string ProspectImportFromCsvFileInDatabaseRequest_Unsuccessprospectimported {
            get {
                return ResourceManager.GetString("ProspectImportFromCsvFileInDatabaseRequest_Unsuccessprospectimported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Subject is Required..
        /// </summary>
        public static string SendEmailRequestValidator_email_subject_Required {
            get {
                return ResourceManager.GetString("SendEmailRequestValidator_email_subject_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email_to is Required..
        /// </summary>
        public static string SendEmailRequestValidator_email_to_Required {
            get {
                return ResourceManager.GetString("SendEmailRequestValidator_email_to_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification_type is Required..
        /// </summary>
        public static string SendEmailRequestValidator_notification_type_Required {
            get {
                return ResourceManager.GetString("SendEmailRequestValidator_notification_type_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is Inactivated..
        /// </summary>
        public static string UpdateContactRequestValidator_ContactInactive {
            get {
                return ResourceManager.GetString("UpdateContactRequestValidator_ContactInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListId is required..
        /// </summary>
        public static string UpdateExpirationRequestValidator_listId_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateExpirationRequestValidator_listId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to update this note..
        /// </summary>
        public static string UpdateNotesRequestValidator_NotesAuth {
            get {
                return ResourceManager.GetString("UpdateNotesRequestValidator_NotesAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line1 should not exceed more than 60 characters..
        /// </summary>
        public static string UpdateProspectRequestValidator_AddressLine1_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_AddressLine1_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1 is required..
        /// </summary>
        public static string UpdateProspectRequestValidator_AddressLine1_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_AddressLine1_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line2 should not exceed more than 60 characters..
        /// </summary>
        public static string UpdateProspectRequestValidator_AddressLine2_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_AddressLine2_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier is Inactivated.
        /// </summary>
        public static string UpdateProspectRequestValidator_CarrierInactive {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_CarrierInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is inactivated..
        /// </summary>
        public static string UpdateProspectRequestValidator_ContactInactive {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_ContactInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIN already exists.
        /// </summary>
        public static string UpdateProspectRequestValidator_EIN {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_EIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect has different EIN saved..
        /// </summary>
        public static string UpdateProspectRequestValidator_EIN_Exists {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_EIN_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EIN.
        /// </summary>
        public static string UpdateProspectRequestValidator_EIN_Format {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_EIN_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EXPMOD..
        /// </summary>
        public static string UpdateProspectRequestValidator_EXPMOD_Format {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_EXPMOD_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPMOD  Length should not exceed more than 5 digits..
        /// </summary>
        public static string UpdateProspectRequestValidator_EXPMOD_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_EXPMOD_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrimary is disabled, as a Primary Contact already exists..
        /// </summary>
        public static string UpdateProspectRequestValidator_IsPrimary_Disabled {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_IsPrimary_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title should not exceed more than 60 characters..
        /// </summary>
        public static string UpdateProspectRequestValidator_JobTitle_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_JobTitle_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title is required..
        /// </summary>
        public static string UpdateProspectRequestValidator_JobTitle_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_JobTitle_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employees should not exceed more than 16 digits..
        /// </summary>
        public static string UpdateProspectRequestValidator_NoOfEmployee_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_NoOfEmployee_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office1Extension should not exceed more than 5 characters..
        /// </summary>
        public static string UpdateProspectRequestValidator_Office1Extension_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_Office1Extension_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Carrier should not exceed more than 16 digits..
        /// </summary>
        public static string UpdateProspectRequestValidator_PackageCarrier_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PackageCarrier_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Package Expiration Date..
        /// </summary>
        public static string UpdateProspectRequestValidator_PackageExpirationDate {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PackageExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Premium should not exceed more than 16 digits..
        /// </summary>
        public static string UpdateProspectRequestValidator_PackagePremium_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PackagePremium_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is requried..
        /// </summary>
        public static string UpdateProspectRequestValidator_PrimaryEmail_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PrimaryEmail_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name should not exceed more than 30 characters..
        /// </summary>
        public static string UpdateProspectRequestValidator_PrimaryFirstName_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PrimaryFirstName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact First Name is required..
        /// </summary>
        public static string UpdateProspectRequestValidator_PrimaryFirstName_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PrimaryFirstName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name should not exceed more than 30 characters..
        /// </summary>
        public static string UpdateProspectRequestValidator_PrimaryLastName_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PrimaryLastName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Last Name is required..
        /// </summary>
        public static string UpdateProspectRequestValidator_PrimaryLastName_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PrimaryLastName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Phone Number is required..
        /// </summary>
        public static string UpdateProspectRequestValidator_PrimaryPhoneNumber_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_PrimaryPhoneNumber_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProspectId can not be 0..
        /// </summary>
        public static string UpdateProspectRequestValidator_ProspectId_NotNull {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_ProspectId_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect is Inactivated..
        /// </summary>
        public static string UpdateProspectRequestValidator_ProspectInactive {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_ProspectInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue should not exceed more than 16 digits..
        /// </summary>
        public static string UpdateProspectRequestValidator_Revenue_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_Revenue_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers Compensation Carrier should not exceed more than 16 digits..
        /// </summary>
        public static string UpdateProspectRequestValidator_WorkersCompensationCarrier_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_WorkersCompensationCarrier_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Workers Compensation Expiration Date..
        /// </summary>
        public static string UpdateProspectRequestValidator_WorkersCompensationExpirationDate {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_WorkersCompensationExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers Compensation Premium should not exceed more than 16 characters..
        /// </summary>
        public static string UpdateProspectRequestValidator_WorkersCompensationPremium_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_WorkersCompensationPremium_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years in Business should not exceed more than 16 digits..
        /// </summary>
        public static string UpdateProspectRequestValidator_YearsInBusiness_Length {
            get {
                return ResourceManager.GetString("UpdateProspectRequestValidator_YearsInBusiness_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level is required.
        /// </summary>
        public static string UpdateUserRequestValidator_AccessLevel_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateUserRequestValidator_AccessLevel_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Id is required..
        /// </summary>
        public static string UpdateUserRequestValidator_BranchId_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateUserRequestValidator_BranchId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epiclookup code is required..
        /// </summary>
        public static string UpdateUserRequestValidator_EPICLookupCode_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateUserRequestValidator_EPICLookupCode_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is required..
        /// </summary>
        public static string UpdateUserRequestValidator_UserId_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateUserRequestValidator_UserId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Id is required..
        /// </summary>
        public static string UpdateWBARequestValidator_ContactId_NotEmpty {
            get {
                return ResourceManager.GetString("UpdateWBARequestValidator_ContactId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Premium should not be exceed more than 16 digits..
        /// </summary>
        public static string UpdateWBARequestValidator_TargetPremium_Length {
            get {
                return ResourceManager.GetString("UpdateWBARequestValidator_TargetPremium_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Premium should be required..
        /// </summary>
        public static string UpdateWBARequestValidator_TargetPremium_Required {
            get {
                return ResourceManager.GetString("UpdateWBARequestValidator_TargetPremium_Required", resourceCulture);
            }
        }
    }
}
