-- Table: public."AcmeProduct"
CREATE TABLE IF NOT EXISTS public."AcmeProduct"
(
    "Id" character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    "Code" character varying(100) COLLATE pg_catalog."default",
    "SKU" character varying(100) COLLATE pg_catalog."default",
    "Name" character varying(200) COLLATE pg_catalog."default",
    "DisplayName" character varying(200) COLLATE pg_catalog."default",
    "ShortName" character varying(200) COLLATE pg_catalog."default",
    "Description" text COLLATE pg_catalog."default",
    "ProductType" character varying(200) COLLATE pg_catalog."default",
    "BaseCost" numeric(18,2),
    "BasePrice" numeric(18,2),
    "Currency" character varying(50) COLLATE pg_catalog."default",
	"ProductOwnerId" character varying(100) COLLATE pg_catalog."default",
    "ProductOwner" character varying(100) COLLATE pg_catalog."default",
    "ProductCode" character varying(100) COLLATE pg_catalog."default",
    "ProductActive" boolean,
	"SalesStartDate" date,
    "SalesEndDate" date,
	"SupportStartDate" date,
    "SupportEndDate" date,
    "VendorId" character varying(100) COLLATE pg_catalog."default",
    "VendorName" character varying(200) COLLATE pg_catalog."default",
	"ProductCategoryId" character varying(100) COLLATE pg_catalog."default",
	"ProductCategory" character varying(200) COLLATE pg_catalog."default",
	"ManufacturerId" character varying(100) COLLATE pg_catalog."default",
    "Manufacturer" character varying(200) COLLATE pg_catalog."default",
    "UnitPrice" numeric(18,2),
    "CommissionRate" numeric(5,2),
	"TaxId" character varying(100) COLLATE pg_catalog."default",
    "Tax" character varying(200) COLLATE pg_catalog."default",
    "UsageUnitId" character varying(100) COLLATE pg_catalog."default",
    "UsageUnit" character varying(200) COLLATE pg_catalog."default",
    "QuantityInStock" integer,
	"HandlerId" character varying(100) COLLATE pg_catalog."default",
    "Handler" character varying(200) COLLATE pg_catalog."default",
    "QuantityOrdered" integer,
    "ReorderLevel" integer,
    "QuantityInDemand" integer,
    "CreatedBy" character varying(100) COLLATE pg_catalog."default",
    "CreatedDateTime" timestamp with time zone default now(),
    "UpdatedBy" character varying(100) COLLATE pg_catalog."default",
    "UpdatedDateTime" timestamp with time zone default now(),
    "UpdateReason" text COLLATE pg_catalog."default",
    "IsActive" boolean DEFAULT true,
    "IsDeleted" boolean DEFAULT false,
    "IsApproved" boolean,
    "ApproverId" character varying(100) COLLATE pg_catalog."default",
    "ApprovedDateTime" timestamp with time zone,
    "IsAuthorized" boolean,
    "AuthorizedById" character varying(100) COLLATE pg_catalog."default",
    "AuthorizedDateTime" timestamp with time zone,
    "SysData" text COLLATE pg_catalog."default",
    "TenantId" character varying(100) COLLATE pg_catalog."default",
    "SubTenantId" character varying(100) COLLATE pg_catalog."default",
    "CustomFields" text COLLATE pg_catalog."default",
    CONSTRAINT "Product_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Product_Code_key" UNIQUE ("Code")
)