//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldPermissions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldPermissions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FieldPermissions", typeof(FieldPermissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanEditAcmeOrder.AcmeOrderId.
        /// </summary>
        public static string CanEditAcmeOrder_AcmeOrderId {
            get {
                return ResourceManager.GetString("CanEditAcmeOrder_AcmeOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanEditAcmeOrder.Subject.
        /// </summary>
        public static string CanEditAcmeOrder_Subject {
            get {
                return ResourceManager.GetString("CanEditAcmeOrder_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanEditAcmeOrder_Subject1.
        /// </summary>
        public static string CanEditAcmeOrder_Subject1 {
            get {
                return ResourceManager.GetString("CanEditAcmeOrder_Subject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanEditAcmeProduct.Name.
        /// </summary>
        public static string CanEditAcmeProduct_Name {
            get {
                return ResourceManager.GetString("CanEditAcmeProduct_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanEditTodoItem.Note.
        /// </summary>
        public static string CanEditTodoItem_Note {
            get {
                return ResourceManager.GetString("CanEditTodoItem_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanEditTodoItem.Title.
        /// </summary>
        public static string CanEditTodoItem_Title {
            get {
                return ResourceManager.GetString("CanEditTodoItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanEditTodoList.Desc.
        /// </summary>
        public static string CanEditTodoList_Desc {
            get {
                return ResourceManager.GetString("CanEditTodoList_Desc", resourceCulture);
            }
        }
    }
}
